apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-worker-config
  namespace: payments-worker
  labels:
    app: payments-worker
data:
  AWS__Region: "us-east-1"
  AWS__AccountId: "${ACC_ID}"
  PaymentsApi__BaseUrl: "http://payments-service.payments.svc.cluster.local"
