apiVersion: v1
kind: Secret
metadata:
  name: payments-worker-secret
  namespace: payments-worker
  labels:
    app: payments-worker
type: Opaque
stringData:
  AWS__AccessKey: "${KEY_ID}"
  AWS__SecretKey: "${KEY_SECRET}"
  AWS__SessionToken: "${KEY_TOKEN}"
  PaymentsApi__InternalToken: "${INTERNAL_AUTH_TOKEN}"
