apiVersion: v1
kind: Secret
metadata:
  name: payments-worker-secret
  namespace: payments-worker
  labels:
    app: payments-worker
type: Opaque
stringData:
  AWS__AccessKey: "${AWS_ACCESS_KEY_ID}"
  AWS__SecretKey: "${AWS_SECRET_ACCESS_KEY}"
  AWS__SessionToken: "${AWS_SESSION_TOKEN}"
  PaymentsApi__InternalToken: "${INTERNAL_AUTH_TOKEN}"
